language: cpp

os:
  - osx
  - windows

compiler:
  - cmake

before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        powershell wget https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh -OutFile ./install-qt.sh
        ./install-qt.sh
        ;;
    esac

addons:
  homebrew:
    packages:
      - qt

script:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
    cmake && nmake ;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    cmake . && make ;
    fi

after_success:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    - macdeployqt tidal-rpc.app
    - zip -r tidal-rpc-osx.zip tidal-rpc.app;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
  - windeployqt  tidal-rpc.exe
  - mkdir Release
  - copy *.exe  Release
  - copy *.dll Release
  - echo D | xcopy /s imageformats "Release/imageformats"
  - echo D | xcopy /s platforms "Release/platforms"
  - echo D | xcopy /s styles "Release/styles"
  - copy LICENSE Release
  - cd Release
  - 7z  a -tzip "tidal-rpc-win.zip"
  - copy tidal-rpc-win.zip ..
    fi

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "tidal-rpc-osx.zip"
    - "tidal-rpc-win.zip"
  skip_cleanup: true
  draft: true