version: 1.3.0.{build}

branches:
  only:
    - master

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=4

  matrix:
    - ARCH: x64
      COMPILER: VS2019
      QTDIR: C:\Qt\5.15.2\msvc2019_64

    - ARCH: x64
      COMPILER: Clang

image:
  - Visual Studio 2019
  - macOS-Mojave
platform:
  - x64
configuration:
  - Release


matrix:
  exclude:
    # Exclude invalid options
    - image: Visual Studio 2019
      COMPILER: CLang

    - image: macos-mojave
      COMPILER: VS2019

for:
  - # Windows
    matrix:
      only:
        - image: Visual Studio 2019

    before_build:
      - set SOURCEDIR=%cd%
      - call %QTDIR%\bin\qtenv2.bat
      - cd /D %SOURCEDIR%
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

    build_script:
      - mkdir .\build
      - cd .\build
      - cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ../
      - cmake --build .
      - call %QTDIR%\bin\windeployqt --release tidal-rpc.exe

    after_build:
      - echo zipping %APPVEYOR_BUILD_VERSION%
      - 7z tidal-rpc.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%/tidal-rpc.exe %APPVEYOR_BUILD_FOLDER%/*.dll %APPVEYOR_BUILD_FOLDER%/imageformats/*.dll %APPVEYOR_BUILD_FOLDER%/platforms/*.dll %APPVEYOR_BUILD_FOLDER%/styles/*.dll

    artifacts:
      - path: tidal-rpc.%APPVEYOR_BUILD_VERSION%.zip

  - # Mac
    matrix:
      only:
        - image: macos-mojave

    before_build:
      - export PATH=$HOME/Qt/5.15.2/clang_64/bin:$PATH

    build_script:
      - mkdir .\build
      - cd .\build
      - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ../
      - cmake --build .
      - $HOME/Qt/5.15.2/clang_64/bin/macdeployqt tidal-rpc.app


    artifacts:
      - path: build/tidal-rpc.app
